### ISSUE TITLE
Post Query Question

### ISSUE THREAD

**Issue by puneetsngh** [nblackburn/devrant-api#1]
I want to use post method for [devrant bot](https://github.com/puneetsngh/devrantbot). Can you tell me the endpoint for auth-token. 

I am getting invalid login credentials error
`https://www.devrant.io/api/users/auth-token?email=$$$$$$$&password=$$$$$&app=3`

**Comment by nblackburn** [comment]
You will need the auth method in [users.js](https://github.com/nblackburn/devrant-api/blob/master/source/users.js#L60-L76)
